// Code generated by gobind. DO NOT EDIT.

// Java class libcore.BoxInstance is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java libcore
package libcore;

import go.Seq;

public final class BoxInstance implements Seq.Proxy {
	static { Libcore.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	BoxInstance(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public BoxInstance() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field BoxInstance.Box with unsupported type: invalid type
	
	public native void close() throws Exception;
	public native long queryStats(String tag, String direct);
	public native boolean selectOutbound(String tag);
	public native void setAsMain();
	public native void setV2rayStats(String outbounds);
	public native void sleep();
	public native void start() throws Exception;
	public native void wake();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof BoxInstance)) {
		    return false;
		}
		BoxInstance that = (BoxInstance)o;
		// skipped field BoxInstance.Box with unsupported type: invalid type
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("BoxInstance").append("{");
		return b.append("}").toString();
	}
}

