// Code generated by gobind. DO NOT EDIT.

// Java class libcore.BoxPlatformInterface is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java libcore
package libcore;

import go.Seq;

public interface BoxPlatformInterface {
	public void autoDetectInterfaceControl(int fd) throws Exception;
	public int findConnectionOwner(int ipProtocol, String sourceAddress, int sourcePort, String destinationAddress, int destinationPort) throws Exception;
	public long openTun(String singTunOptionsJson, String tunPlatformOptionsJson) throws Exception;
	public String packageNameByUid(int uid) throws Exception;
	public int uidByPackageName(String packageName) throws Exception;
	public boolean useProcFS();
	public String wifiState();
	
}

