// Code generated by gobind. DO NOT EDIT.

// Java class libcore.Func is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java libcore
package libcore;

import go.Seq;

public interface Func {
	public void invoke() throws Exception;
	
}

