// Code generated by gobind. DO NOT EDIT.

// Java class libcore.HTTPResponse is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java libcore
package libcore;

import go.Seq;

public interface HTTPResponse {
	public byte[] getContent() throws Exception;
	public StringBox getContentString() throws Exception;
	public StringBox getHeader(String p0);
	public void writeTo(String path) throws Exception;
	
}

