// Code generated by gobind. DO NOT EDIT.

// Java class libcore.LocalDNSTransport is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java libcore
package libcore;

import go.Seq;

public interface LocalDNSTransport {
	public void exchange(ExchangeContext ctx, byte[] message) throws Exception;
	public void lookup(ExchangeContext ctx, String network, String domain) throws Exception;
	public long networkHandle();
	public boolean raw();
	
}

