// Code generated by gobind. DO NOT EDIT.

// Java class libcore.NB4AInterface is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java libcore
package libcore;

import go.Seq;

public interface NB4AInterface {
	public void selector_OnProxySelected(String selectorTag, String tag);
	public boolean useOfficialAssets();
	
}

