// Code generated by gobind. DO NOT EDIT.

// Java class libcore.StringBox is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java libcore
package libcore;

import go.Seq;

public final class StringBox implements Seq.Proxy {
	static { Libcore.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	StringBox(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public StringBox() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native String getValue();
	public final native void setValue(String v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof StringBox)) {
		    return false;
		}
		StringBox that = (StringBox)o;
		String thisValue = getValue();
		String thatValue = that.getValue();
		if (thisValue == null) {
			if (thatValue != null) {
			    return false;
			}
		} else if (!thisValue.equals(thatValue)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getValue()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("StringBox").append("{");
		b.append("Value:").append(getValue()).append(",");
		return b.append("}").toString();
	}
}

