// Code generated by gobind. DO NOT EDIT.

// Java class libcore.StunResult is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java libcore
package libcore;

import go.Seq;

public final class StunResult implements Seq.Proxy {
	static { Libcore.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	StunResult(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public StunResult() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native String getText();
	public final native void setText(String v);
	
	public final native boolean getSuccess();
	public final native void setSuccess(boolean v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof StunResult)) {
		    return false;
		}
		StunResult that = (StunResult)o;
		String thisText = getText();
		String thatText = that.getText();
		if (thisText == null) {
			if (thatText != null) {
			    return false;
			}
		} else if (!thisText.equals(thatText)) {
		    return false;
		}
		boolean thisSuccess = getSuccess();
		boolean thatSuccess = that.getSuccess();
		if (thisSuccess != thatSuccess) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getText(), getSuccess()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("StunResult").append("{");
		b.append("Text:").append(getText()).append(",");
		b.append("Success:").append(getSuccess()).append(",");
		return b.append("}").toString();
	}
}

