// Code generated by gobind. DO NOT EDIT.

// JNI function headers for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java with_conntrack,with_gvisor,with_quic,with_wireguard,with_utls,with_clash_api

#ifndef ___H__
#define ___H__

#include <jni.h>

#endif
