// Code generated by gobind. DO NOT EDIT.

// JNI functions for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java libcore

#include <android/log.h>
#include <stdio.h>
#include <stdint.h>
#include "seq.h"
#include "_cgo_export.h"
#include "libcore.h"

static void trace_jni(const char* message) {
	FILE* file = fopen("jni_trace.txt", "a");
	if (file == NULL) {
		return;
	}
	fprintf(file, "%s\n", message);
	fclose(file);
}

jclass proxy_class_libcore_BoxPlatformInterface;
jmethodID proxy_class_libcore_BoxPlatformInterface_cons;
static jmethodID mid_BoxPlatformInterface_AutoDetectInterfaceControl;
static jmethodID mid_BoxPlatformInterface_FindConnectionOwner;
static jmethodID mid_BoxPlatformInterface_OpenTun;
static jmethodID mid_BoxPlatformInterface_PackageNameByUid;
static jmethodID mid_BoxPlatformInterface_UIDByPackageName;
static jmethodID mid_BoxPlatformInterface_UseProcFS;
static jmethodID mid_BoxPlatformInterface_WIFIState;
jclass proxy_class_libcore_Func;
jmethodID proxy_class_libcore_Func_cons;
static jmethodID mid_Func_Invoke;
jclass proxy_class_libcore_HTTPClient;
jmethodID proxy_class_libcore_HTTPClient_cons;
static jmethodID mid_HTTPClient_Close;
static jmethodID mid_HTTPClient_KeepAlive;
static jmethodID mid_HTTPClient_ModernTLS;
static jmethodID mid_HTTPClient_NewRequest;
static jmethodID mid_HTTPClient_PinnedSHA256;
static jmethodID mid_HTTPClient_PinnedTLS12;
static jmethodID mid_HTTPClient_RestrictedTLS;
static jmethodID mid_HTTPClient_TryH3Direct;
static jmethodID mid_HTTPClient_TrySocks5;
jclass proxy_class_libcore_HTTPRequest;
jmethodID proxy_class_libcore_HTTPRequest_cons;
static jmethodID mid_HTTPRequest_AllowInsecure;
static jmethodID mid_HTTPRequest_Execute;
static jmethodID mid_HTTPRequest_SetContent;
static jmethodID mid_HTTPRequest_SetContentString;
static jmethodID mid_HTTPRequest_SetHeader;
static jmethodID mid_HTTPRequest_SetMethod;
static jmethodID mid_HTTPRequest_SetURL;
static jmethodID mid_HTTPRequest_SetUserAgent;
jclass proxy_class_libcore_HTTPResponse;
jmethodID proxy_class_libcore_HTTPResponse_cons;
static jmethodID mid_HTTPResponse_GetContent;
static jmethodID mid_HTTPResponse_GetContentString;
static jmethodID mid_HTTPResponse_GetHeader;
static jmethodID mid_HTTPResponse_WriteTo;
jclass proxy_class_libcore_LocalDNSTransport;
jmethodID proxy_class_libcore_LocalDNSTransport_cons;
static jmethodID mid_LocalDNSTransport_Exchange;
static jmethodID mid_LocalDNSTransport_Lookup;
static jmethodID mid_LocalDNSTransport_NetworkHandle;
static jmethodID mid_LocalDNSTransport_Raw;
jclass proxy_class_libcore_NB4AInterface;
jmethodID proxy_class_libcore_NB4AInterface_cons;
static jmethodID mid_NB4AInterface_Selector_OnProxySelected;
static jmethodID mid_NB4AInterface_UseOfficialAssets;
jclass proxy_class_libcore_BoxInstance;
jmethodID proxy_class_libcore_BoxInstance_cons;
jclass proxy_class_libcore_ExchangeContext;
jmethodID proxy_class_libcore_ExchangeContext_cons;
jclass proxy_class_libcore_StringBox;
jmethodID proxy_class_libcore_StringBox_cons;
jclass proxy_class_libcore_StunResult;
jmethodID proxy_class_libcore_StunResult_cons;

JNIEXPORT void JNICALL
Java_libcore_Libcore__1init(JNIEnv *env, jclass _unused) {
	jclass clazz;
	clazz = (*env)->FindClass(env, "libcore/BoxInstance");
	proxy_class_libcore_BoxInstance = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_BoxInstance_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/ExchangeContext");
	proxy_class_libcore_ExchangeContext = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_ExchangeContext_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/StringBox");
	proxy_class_libcore_StringBox = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_StringBox_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/StunResult");
	proxy_class_libcore_StunResult = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_StunResult_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/Libcore$proxyBoxPlatformInterface");
	proxy_class_libcore_BoxPlatformInterface = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_BoxPlatformInterface_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/BoxPlatformInterface");
	mid_BoxPlatformInterface_AutoDetectInterfaceControl = (*env)->GetMethodID(env, clazz, "autoDetectInterfaceControl", "(I)V");
	mid_BoxPlatformInterface_FindConnectionOwner = (*env)->GetMethodID(env, clazz, "findConnectionOwner", "(ILjava/lang/String;ILjava/lang/String;I)I");
	mid_BoxPlatformInterface_OpenTun = (*env)->GetMethodID(env, clazz, "openTun", "(Ljava/lang/String;Ljava/lang/String;)J");
	mid_BoxPlatformInterface_PackageNameByUid = (*env)->GetMethodID(env, clazz, "packageNameByUid", "(I)Ljava/lang/String;");
	mid_BoxPlatformInterface_UIDByPackageName = (*env)->GetMethodID(env, clazz, "uidByPackageName", "(Ljava/lang/String;)I");
	mid_BoxPlatformInterface_UseProcFS = (*env)->GetMethodID(env, clazz, "useProcFS", "()Z");
	mid_BoxPlatformInterface_WIFIState = (*env)->GetMethodID(env, clazz, "wifiState", "()Ljava/lang/String;");
	
	clazz = (*env)->FindClass(env, "libcore/Libcore$proxyFunc");
	proxy_class_libcore_Func = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_Func_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/Func");
	mid_Func_Invoke = (*env)->GetMethodID(env, clazz, "invoke", "()V");
	
	clazz = (*env)->FindClass(env, "libcore/Libcore$proxyHTTPClient");
	proxy_class_libcore_HTTPClient = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_HTTPClient_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/HTTPClient");
	mid_HTTPClient_Close = (*env)->GetMethodID(env, clazz, "close", "()V");
	mid_HTTPClient_KeepAlive = (*env)->GetMethodID(env, clazz, "keepAlive", "()V");
	mid_HTTPClient_ModernTLS = (*env)->GetMethodID(env, clazz, "modernTLS", "()V");
	mid_HTTPClient_NewRequest = (*env)->GetMethodID(env, clazz, "newRequest", "()Llibcore/HTTPRequest;");
	mid_HTTPClient_PinnedSHA256 = (*env)->GetMethodID(env, clazz, "pinnedSHA256", "(Ljava/lang/String;)V");
	mid_HTTPClient_PinnedTLS12 = (*env)->GetMethodID(env, clazz, "pinnedTLS12", "()V");
	mid_HTTPClient_RestrictedTLS = (*env)->GetMethodID(env, clazz, "restrictedTLS", "()V");
	mid_HTTPClient_TryH3Direct = (*env)->GetMethodID(env, clazz, "tryH3Direct", "()V");
	mid_HTTPClient_TrySocks5 = (*env)->GetMethodID(env, clazz, "trySocks5", "(I)V");
	
	clazz = (*env)->FindClass(env, "libcore/Libcore$proxyHTTPRequest");
	proxy_class_libcore_HTTPRequest = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_HTTPRequest_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/HTTPRequest");
	mid_HTTPRequest_AllowInsecure = (*env)->GetMethodID(env, clazz, "allowInsecure", "()V");
	mid_HTTPRequest_Execute = (*env)->GetMethodID(env, clazz, "execute", "()Llibcore/HTTPResponse;");
	mid_HTTPRequest_SetContent = (*env)->GetMethodID(env, clazz, "setContent", "([B)V");
	mid_HTTPRequest_SetContentString = (*env)->GetMethodID(env, clazz, "setContentString", "(Ljava/lang/String;)V");
	mid_HTTPRequest_SetHeader = (*env)->GetMethodID(env, clazz, "setHeader", "(Ljava/lang/String;Ljava/lang/String;)V");
	mid_HTTPRequest_SetMethod = (*env)->GetMethodID(env, clazz, "setMethod", "(Ljava/lang/String;)V");
	mid_HTTPRequest_SetURL = (*env)->GetMethodID(env, clazz, "setURL", "(Ljava/lang/String;)V");
	mid_HTTPRequest_SetUserAgent = (*env)->GetMethodID(env, clazz, "setUserAgent", "(Ljava/lang/String;)V");
	
	clazz = (*env)->FindClass(env, "libcore/Libcore$proxyHTTPResponse");
	proxy_class_libcore_HTTPResponse = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_HTTPResponse_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/HTTPResponse");
	mid_HTTPResponse_GetContent = (*env)->GetMethodID(env, clazz, "getContent", "()[B");
	mid_HTTPResponse_GetContentString = (*env)->GetMethodID(env, clazz, "getContentString", "()Llibcore/StringBox;");
	mid_HTTPResponse_GetHeader = (*env)->GetMethodID(env, clazz, "getHeader", "(Ljava/lang/String;)Llibcore/StringBox;");
	mid_HTTPResponse_WriteTo = (*env)->GetMethodID(env, clazz, "writeTo", "(Ljava/lang/String;)V");
	
	clazz = (*env)->FindClass(env, "libcore/Libcore$proxyLocalDNSTransport");
	proxy_class_libcore_LocalDNSTransport = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_LocalDNSTransport_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/LocalDNSTransport");
	mid_LocalDNSTransport_Exchange = (*env)->GetMethodID(env, clazz, "exchange", "(Llibcore/ExchangeContext;[B)V");
	mid_LocalDNSTransport_Lookup = (*env)->GetMethodID(env, clazz, "lookup", "(Llibcore/ExchangeContext;Ljava/lang/String;Ljava/lang/String;)V");
	mid_LocalDNSTransport_NetworkHandle = (*env)->GetMethodID(env, clazz, "networkHandle", "()J");
	mid_LocalDNSTransport_Raw = (*env)->GetMethodID(env, clazz, "raw", "()Z");
	
	clazz = (*env)->FindClass(env, "libcore/Libcore$proxyNB4AInterface");
	proxy_class_libcore_NB4AInterface = (*env)->NewGlobalRef(env, clazz);
	proxy_class_libcore_NB4AInterface_cons = (*env)->GetMethodID(env, clazz, "<init>", "(I)V");
	clazz = (*env)->FindClass(env, "libcore/NB4AInterface");
	mid_NB4AInterface_Selector_OnProxySelected = (*env)->GetMethodID(env, clazz, "selector_OnProxySelected", "(Ljava/lang/String;Ljava/lang/String;)V");
	mid_NB4AInterface_UseOfficialAssets = (*env)->GetMethodID(env, clazz, "useOfficialAssets", "()Z");
	
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_forceGc(JNIEnv* env, jclass _clazz) {
	proxylibcore__ForceGc();
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_initCore(JNIEnv* env, jclass _clazz, jstring process, jstring cachePath, jstring internalAssets, jstring externalAssets, jint maxLogSizeKb, jboolean logEnable, jobject if1, jobject if2, jobject if3) {
	nstring _process = go_seq_from_java_string(env, process);
	nstring _cachePath = go_seq_from_java_string(env, cachePath);
	nstring _internalAssets = go_seq_from_java_string(env, internalAssets);
	nstring _externalAssets = go_seq_from_java_string(env, externalAssets);
	int32_t _maxLogSizeKb = (int32_t)maxLogSizeKb;
	char _logEnable = (char)logEnable;
	int32_t _if1 = go_seq_to_refnum(env, if1);
	int32_t _if2 = go_seq_to_refnum(env, if2);
	int32_t _if3 = go_seq_to_refnum(env, if3);
	proxylibcore__InitCore(_process, _cachePath, _internalAssets, _externalAssets, _maxLogSizeKb, _logEnable, _if1, _if2, _if3);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_nekoLogClear(JNIEnv* env, jclass _clazz) {
	proxylibcore__NekoLogClear();
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_nekoLogPrintln(JNIEnv* env, jclass _clazz, jstring s) {
	nstring _s = go_seq_from_java_string(env, s);
	proxylibcore__NekoLogPrintln(_s);
}

JNIEXPORT jobject JNICALL
Java_libcore_Libcore_newHttpClient(JNIEnv* env, jclass _clazz) {
	int32_t r0 = proxylibcore__NewHttpClient();
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class_libcore_HTTPClient, proxy_class_libcore_HTTPClient_cons);
	return _r0;
}

JNIEXPORT jobject JNICALL
Java_libcore_Libcore_newSingBoxInstance(JNIEnv* env, jclass _clazz, jstring config, jobject localTransport) {
	trace_jni("Java_libcore_Libcore_newSingBoxInstance enter");
	nstring _config = go_seq_from_java_string(env, config);
	trace_jni("Java_libcore_Libcore_newSingBoxInstance after go_seq_from_java_string");
	int32_t _localTransport = go_seq_to_refnum(env, localTransport);
	trace_jni("Java_libcore_Libcore_newSingBoxInstance after go_seq_to_refnum");
	struct proxylibcore__NewSingBoxInstance_return res = proxylibcore__NewSingBoxInstance(_config, _localTransport);
	trace_jni("Java_libcore_Libcore_newSingBoxInstance after proxylibcore__NewSingBoxInstance");
	jobject _r0 = go_seq_from_refnum(env, res.r0, proxy_class_libcore_BoxInstance, proxy_class_libcore_BoxInstance_cons);
	trace_jni("Java_libcore_Libcore_newSingBoxInstance after go_seq_from_refnum box");
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	trace_jni("Java_libcore_Libcore_newSingBoxInstance after go_seq_from_refnum error");
	go_seq_maybe_throw_exception(env, _r1);
	trace_jni("Java_libcore_Libcore_newSingBoxInstance before return");
	return _r0;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_resetAllConnections(JNIEnv* env, jclass _clazz, jboolean system) {
	char _system = (char)system;
	proxylibcore__ResetAllConnections(_system);
}

JNIEXPORT jbyteArray JNICALL
Java_libcore_Libcore_sha1(JNIEnv* env, jclass _clazz, jbyteArray data) {
	nbyteslice _data = go_seq_from_java_bytearray(env, data, 0);
	nbyteslice r0 = proxylibcore__Sha1(_data);
	go_seq_release_byte_array(env, data, _data.ptr);
	jbyteArray _r0 = go_seq_to_java_bytearray(env, r0, 1);
	return _r0;
}

JNIEXPORT jstring JNICALL
Java_libcore_Libcore_sha256Hex(JNIEnv* env, jclass _clazz, jbyteArray data) {
	nbyteslice _data = go_seq_from_java_bytearray(env, data, 0);
	nstring r0 = proxylibcore__Sha256Hex(_data);
	go_seq_release_byte_array(env, data, _data.ptr);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT jobject JNICALL
Java_libcore_Libcore_stunTest(JNIEnv* env, jclass _clazz, jstring server) {
	nstring _server = go_seq_from_java_string(env, server);
	int32_t r0 = proxylibcore__StunTest(_server);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class_libcore_StunResult, proxy_class_libcore_StunResult_cons);
	return _r0;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_unxz(JNIEnv* env, jclass _clazz, jstring archive, jstring path) {
	nstring _archive = go_seq_from_java_string(env, archive);
	nstring _path = go_seq_from_java_string(env, path);
	int32_t r0 = proxylibcore__Unxz(_archive, _path);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_unzip(JNIEnv* env, jclass _clazz, jstring archive, jstring path) {
	nstring _archive = go_seq_from_java_string(env, archive);
	nstring _path = go_seq_from_java_string(env, path);
	int32_t r0 = proxylibcore__Unzip(_archive, _path);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT jint JNICALL
Java_libcore_Libcore_urlTest(JNIEnv* env, jclass _clazz, jobject i, jstring link, jint timeout) {
	int32_t _i = go_seq_to_refnum(env, i);
	nstring _link = go_seq_from_java_string(env, link);
	int32_t _timeout = (int32_t)timeout;
	struct proxylibcore__UrlTest_return res = proxylibcore__UrlTest(_i, _link, _timeout);
	jint _r0 = (jint)res.r0;
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

JNIEXPORT jstring JNICALL
Java_libcore_Libcore_versionBox(JNIEnv* env, jclass _clazz) {
	nstring r0 = proxylibcore__VersionBox();
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT jint JNICALL
Java_libcore_BoxInstance__1_1New(JNIEnv *env, jclass clazz) {
	return new_libcore_BoxInstance();
}

JNIEXPORT void JNICALL
Java_libcore_BoxInstance_close(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t r0 = proxylibcore_BoxInstance_Close(o);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT jlong JNICALL
Java_libcore_BoxInstance_queryStats(JNIEnv* env, jobject __this__, jstring tag, jstring direct) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _tag = go_seq_from_java_string(env, tag);
	nstring _direct = go_seq_from_java_string(env, direct);
	int64_t r0 = proxylibcore_BoxInstance_QueryStats(o, _tag, _direct);
	jlong _r0 = (jlong)r0;
	return _r0;
}

JNIEXPORT jboolean JNICALL
Java_libcore_BoxInstance_selectOutbound(JNIEnv* env, jobject __this__, jstring tag) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _tag = go_seq_from_java_string(env, tag);
	char r0 = proxylibcore_BoxInstance_SelectOutbound(o, _tag);
	jboolean _r0 = r0 ? JNI_TRUE : JNI_FALSE;
	return _r0;
}

JNIEXPORT void JNICALL
Java_libcore_BoxInstance_setAsMain(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxylibcore_BoxInstance_SetAsMain(o);
}

JNIEXPORT void JNICALL
Java_libcore_BoxInstance_setV2rayStats(JNIEnv* env, jobject __this__, jstring outbounds) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _outbounds = go_seq_from_java_string(env, outbounds);
	proxylibcore_BoxInstance_SetV2rayStats(o, _outbounds);
}

JNIEXPORT void JNICALL
Java_libcore_BoxInstance_sleep(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxylibcore_BoxInstance_Sleep(o);
}

JNIEXPORT void JNICALL
Java_libcore_BoxInstance_start(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t r0 = proxylibcore_BoxInstance_Start(o);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

JNIEXPORT void JNICALL
Java_libcore_BoxInstance_wake(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxylibcore_BoxInstance_Wake(o);
}

// skipped field BoxInstance with unsupported type: invalid type

JNIEXPORT jint JNICALL
Java_libcore_ExchangeContext__1_1New(JNIEnv *env, jclass clazz) {
	return new_libcore_ExchangeContext();
}

JNIEXPORT void JNICALL
Java_libcore_ExchangeContext_errnoCode(JNIEnv* env, jobject __this__, jint code) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t _code = (int32_t)code;
	proxylibcore_ExchangeContext_ErrnoCode(o, _code);
}

JNIEXPORT void JNICALL
Java_libcore_ExchangeContext_errorCode(JNIEnv* env, jobject __this__, jint code) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t _code = (int32_t)code;
	proxylibcore_ExchangeContext_ErrorCode(o, _code);
}

JNIEXPORT void JNICALL
Java_libcore_ExchangeContext_onCancel(JNIEnv* env, jobject __this__, jobject callback) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t _callback = go_seq_to_refnum(env, callback);
	proxylibcore_ExchangeContext_OnCancel(o, _callback);
}

JNIEXPORT void JNICALL
Java_libcore_ExchangeContext_rawSuccess(JNIEnv* env, jobject __this__, jbyteArray result) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nbyteslice _result = go_seq_from_java_bytearray(env, result, 0);
	proxylibcore_ExchangeContext_RawSuccess(o, _result);
	go_seq_release_byte_array(env, result, _result.ptr);
}

JNIEXPORT void JNICALL
Java_libcore_ExchangeContext_success(JNIEnv* env, jobject __this__, jstring result) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _result = go_seq_from_java_string(env, result);
	proxylibcore_ExchangeContext_Success(o, _result);
}

JNIEXPORT jint JNICALL
Java_libcore_StringBox__1_1New(JNIEnv *env, jclass clazz) {
	return new_libcore_StringBox();
}

JNIEXPORT void JNICALL
Java_libcore_StringBox_setValue(JNIEnv *env, jobject this, jstring v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring _v = go_seq_from_java_string(env, v);
	proxylibcore_StringBox_Value_Set(o, _v);
}

JNIEXPORT jstring JNICALL
Java_libcore_StringBox_getValue(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring r0 = proxylibcore_StringBox_Value_Get(o);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT jint JNICALL
Java_libcore_StunResult__1_1New(JNIEnv *env, jclass clazz) {
	return new_libcore_StunResult();
}

JNIEXPORT void JNICALL
Java_libcore_StunResult_setText(JNIEnv *env, jobject this, jstring v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring _v = go_seq_from_java_string(env, v);
	proxylibcore_StunResult_Text_Set(o, _v);
}

JNIEXPORT jstring JNICALL
Java_libcore_StunResult_getText(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	nstring r0 = proxylibcore_StunResult_Text_Get(o);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

JNIEXPORT void JNICALL
Java_libcore_StunResult_setSuccess(JNIEnv *env, jobject this, jboolean v) {
	int32_t o = go_seq_to_refnum_go(env, this);
	char _v = (char)v;
	proxylibcore_StunResult_Success_Set(o, _v);
}

JNIEXPORT jboolean JNICALL
Java_libcore_StunResult_getSuccess(JNIEnv *env, jobject this) {
	int32_t o = go_seq_to_refnum_go(env, this);
	char r0 = proxylibcore_StunResult_Success_Get(o);
	jboolean _r0 = r0 ? JNI_TRUE : JNI_FALSE;
	return _r0;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyBoxPlatformInterface_autoDetectInterfaceControl(JNIEnv* env, jobject __this__, jint fd) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t _fd = (int32_t)fd;
	int32_t r0 = proxylibcore_BoxPlatformInterface_AutoDetectInterfaceControl(o, _fd);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

int32_t cproxylibcore_BoxPlatformInterface_AutoDetectInterfaceControl(int32_t refnum, int32_t fd) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_BoxPlatformInterface, proxy_class_libcore_BoxPlatformInterface_cons);
	jint _fd = (jint)fd;
	(*env)->CallVoidMethod(env, o, mid_BoxPlatformInterface_AutoDetectInterfaceControl, _fd);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	go_seq_pop_local_frame(env);
	return _exc;
}

JNIEXPORT jint JNICALL
Java_libcore_Libcore_00024proxyBoxPlatformInterface_findConnectionOwner(JNIEnv* env, jobject __this__, jint ipProtocol, jstring sourceAddress, jint sourcePort, jstring destinationAddress, jint destinationPort) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t _ipProtocol = (int32_t)ipProtocol;
	nstring _sourceAddress = go_seq_from_java_string(env, sourceAddress);
	int32_t _sourcePort = (int32_t)sourcePort;
	nstring _destinationAddress = go_seq_from_java_string(env, destinationAddress);
	int32_t _destinationPort = (int32_t)destinationPort;
	struct proxylibcore_BoxPlatformInterface_FindConnectionOwner_return res = proxylibcore_BoxPlatformInterface_FindConnectionOwner(o, _ipProtocol, _sourceAddress, _sourcePort, _destinationAddress, _destinationPort);
	jint _r0 = (jint)res.r0;
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

struct cproxylibcore_BoxPlatformInterface_FindConnectionOwner_return cproxylibcore_BoxPlatformInterface_FindConnectionOwner(int32_t refnum, int32_t ipProtocol, nstring sourceAddress, int32_t sourcePort, nstring destinationAddress, int32_t destinationPort) {
	JNIEnv *env = go_seq_push_local_frame(5);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_BoxPlatformInterface, proxy_class_libcore_BoxPlatformInterface_cons);
	jint _ipProtocol = (jint)ipProtocol;
	jstring _sourceAddress = go_seq_to_java_string(env, sourceAddress);
	jint _sourcePort = (jint)sourcePort;
	jstring _destinationAddress = go_seq_to_java_string(env, destinationAddress);
	jint _destinationPort = (jint)destinationPort;
	jint res = (*env)->CallIntMethod(env, o, mid_BoxPlatformInterface_FindConnectionOwner, _ipProtocol, _sourceAddress, _sourcePort, _destinationAddress, _destinationPort);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	if (exc != NULL) {
		res = 0;
	}
	int32_t _res = (int32_t)res;
	cproxylibcore_BoxPlatformInterface_FindConnectionOwner_return sres = {
		_res, _exc
	};
	go_seq_pop_local_frame(env);
	return sres;
}

JNIEXPORT jlong JNICALL
Java_libcore_Libcore_00024proxyBoxPlatformInterface_openTun(JNIEnv* env, jobject __this__, jstring singTunOptionsJson, jstring tunPlatformOptionsJson) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _singTunOptionsJson = go_seq_from_java_string(env, singTunOptionsJson);
	nstring _tunPlatformOptionsJson = go_seq_from_java_string(env, tunPlatformOptionsJson);
	struct proxylibcore_BoxPlatformInterface_OpenTun_return res = proxylibcore_BoxPlatformInterface_OpenTun(o, _singTunOptionsJson, _tunPlatformOptionsJson);
	jlong _r0 = (jlong)res.r0;
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

struct cproxylibcore_BoxPlatformInterface_OpenTun_return cproxylibcore_BoxPlatformInterface_OpenTun(int32_t refnum, nstring singTunOptionsJson, nstring tunPlatformOptionsJson) {
	JNIEnv *env = go_seq_push_local_frame(2);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_BoxPlatformInterface, proxy_class_libcore_BoxPlatformInterface_cons);
	jstring _singTunOptionsJson = go_seq_to_java_string(env, singTunOptionsJson);
	jstring _tunPlatformOptionsJson = go_seq_to_java_string(env, tunPlatformOptionsJson);
	jlong res = (*env)->CallLongMethod(env, o, mid_BoxPlatformInterface_OpenTun, _singTunOptionsJson, _tunPlatformOptionsJson);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	if (exc != NULL) {
		res = 0;
	}
	nint _res = (nint)res;
	cproxylibcore_BoxPlatformInterface_OpenTun_return sres = {
		_res, _exc
	};
	go_seq_pop_local_frame(env);
	return sres;
}

JNIEXPORT jstring JNICALL
Java_libcore_Libcore_00024proxyBoxPlatformInterface_packageNameByUid(JNIEnv* env, jobject __this__, jint uid) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t _uid = (int32_t)uid;
	struct proxylibcore_BoxPlatformInterface_PackageNameByUid_return res = proxylibcore_BoxPlatformInterface_PackageNameByUid(o, _uid);
	jstring _r0 = go_seq_to_java_string(env, res.r0);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

struct cproxylibcore_BoxPlatformInterface_PackageNameByUid_return cproxylibcore_BoxPlatformInterface_PackageNameByUid(int32_t refnum, int32_t uid) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_BoxPlatformInterface, proxy_class_libcore_BoxPlatformInterface_cons);
	jint _uid = (jint)uid;
	jstring res = (*env)->CallObjectMethod(env, o, mid_BoxPlatformInterface_PackageNameByUid, _uid);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	if (exc != NULL) {
		res = NULL;
	}
	nstring _res = go_seq_from_java_string(env, res);
	cproxylibcore_BoxPlatformInterface_PackageNameByUid_return sres = {
		_res, _exc
	};
	go_seq_pop_local_frame(env);
	return sres;
}

JNIEXPORT jint JNICALL
Java_libcore_Libcore_00024proxyBoxPlatformInterface_uidByPackageName(JNIEnv* env, jobject __this__, jstring packageName) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _packageName = go_seq_from_java_string(env, packageName);
	struct proxylibcore_BoxPlatformInterface_UIDByPackageName_return res = proxylibcore_BoxPlatformInterface_UIDByPackageName(o, _packageName);
	jint _r0 = (jint)res.r0;
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

struct cproxylibcore_BoxPlatformInterface_UIDByPackageName_return cproxylibcore_BoxPlatformInterface_UIDByPackageName(int32_t refnum, nstring packageName) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_BoxPlatformInterface, proxy_class_libcore_BoxPlatformInterface_cons);
	jstring _packageName = go_seq_to_java_string(env, packageName);
	jint res = (*env)->CallIntMethod(env, o, mid_BoxPlatformInterface_UIDByPackageName, _packageName);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	if (exc != NULL) {
		res = 0;
	}
	int32_t _res = (int32_t)res;
	cproxylibcore_BoxPlatformInterface_UIDByPackageName_return sres = {
		_res, _exc
	};
	go_seq_pop_local_frame(env);
	return sres;
}

JNIEXPORT jboolean JNICALL
Java_libcore_Libcore_00024proxyBoxPlatformInterface_useProcFS(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	char r0 = proxylibcore_BoxPlatformInterface_UseProcFS(o);
	jboolean _r0 = r0 ? JNI_TRUE : JNI_FALSE;
	return _r0;
}

char cproxylibcore_BoxPlatformInterface_UseProcFS(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_BoxPlatformInterface, proxy_class_libcore_BoxPlatformInterface_cons);
	jboolean res = (*env)->CallBooleanMethod(env, o, mid_BoxPlatformInterface_UseProcFS);
	char _res = (char)res;
	go_seq_pop_local_frame(env);
	return _res;
}

JNIEXPORT jstring JNICALL
Java_libcore_Libcore_00024proxyBoxPlatformInterface_wifiState(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring r0 = proxylibcore_BoxPlatformInterface_WIFIState(o);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

nstring cproxylibcore_BoxPlatformInterface_WIFIState(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_BoxPlatformInterface, proxy_class_libcore_BoxPlatformInterface_cons);
	jstring res = (*env)->CallObjectMethod(env, o, mid_BoxPlatformInterface_WIFIState);
	nstring _res = go_seq_from_java_string(env, res);
	go_seq_pop_local_frame(env);
	return _res;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyFunc_invoke(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t r0 = proxylibcore_Func_Invoke(o);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

int32_t cproxylibcore_Func_Invoke(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_Func, proxy_class_libcore_Func_cons);
	(*env)->CallVoidMethod(env, o, mid_Func_Invoke);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	go_seq_pop_local_frame(env);
	return _exc;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPClient_close(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxylibcore_HTTPClient_Close(o);
}

void cproxylibcore_HTTPClient_Close(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPClient, proxy_class_libcore_HTTPClient_cons);
	(*env)->CallVoidMethod(env, o, mid_HTTPClient_Close);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPClient_keepAlive(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxylibcore_HTTPClient_KeepAlive(o);
}

void cproxylibcore_HTTPClient_KeepAlive(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPClient, proxy_class_libcore_HTTPClient_cons);
	(*env)->CallVoidMethod(env, o, mid_HTTPClient_KeepAlive);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPClient_modernTLS(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxylibcore_HTTPClient_ModernTLS(o);
}

void cproxylibcore_HTTPClient_ModernTLS(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPClient, proxy_class_libcore_HTTPClient_cons);
	(*env)->CallVoidMethod(env, o, mid_HTTPClient_ModernTLS);
	go_seq_pop_local_frame(env);
}

JNIEXPORT jobject JNICALL
Java_libcore_Libcore_00024proxyHTTPClient_newRequest(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t r0 = proxylibcore_HTTPClient_NewRequest(o);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class_libcore_HTTPRequest, proxy_class_libcore_HTTPRequest_cons);
	return _r0;
}

int32_t cproxylibcore_HTTPClient_NewRequest(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPClient, proxy_class_libcore_HTTPClient_cons);
	jobject res = (*env)->CallObjectMethod(env, o, mid_HTTPClient_NewRequest);
	int32_t _res = go_seq_to_refnum(env, res);
	go_seq_pop_local_frame(env);
	return _res;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPClient_pinnedSHA256(JNIEnv* env, jobject __this__, jstring sumHex) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _sumHex = go_seq_from_java_string(env, sumHex);
	proxylibcore_HTTPClient_PinnedSHA256(o, _sumHex);
}

void cproxylibcore_HTTPClient_PinnedSHA256(int32_t refnum, nstring sumHex) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPClient, proxy_class_libcore_HTTPClient_cons);
	jstring _sumHex = go_seq_to_java_string(env, sumHex);
	(*env)->CallVoidMethod(env, o, mid_HTTPClient_PinnedSHA256, _sumHex);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPClient_pinnedTLS12(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxylibcore_HTTPClient_PinnedTLS12(o);
}

void cproxylibcore_HTTPClient_PinnedTLS12(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPClient, proxy_class_libcore_HTTPClient_cons);
	(*env)->CallVoidMethod(env, o, mid_HTTPClient_PinnedTLS12);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPClient_restrictedTLS(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxylibcore_HTTPClient_RestrictedTLS(o);
}

void cproxylibcore_HTTPClient_RestrictedTLS(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPClient, proxy_class_libcore_HTTPClient_cons);
	(*env)->CallVoidMethod(env, o, mid_HTTPClient_RestrictedTLS);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPClient_tryH3Direct(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxylibcore_HTTPClient_TryH3Direct(o);
}

void cproxylibcore_HTTPClient_TryH3Direct(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPClient, proxy_class_libcore_HTTPClient_cons);
	(*env)->CallVoidMethod(env, o, mid_HTTPClient_TryH3Direct);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPClient_trySocks5(JNIEnv* env, jobject __this__, jint port) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t _port = (int32_t)port;
	proxylibcore_HTTPClient_TrySocks5(o, _port);
}

void cproxylibcore_HTTPClient_TrySocks5(int32_t refnum, int32_t port) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPClient, proxy_class_libcore_HTTPClient_cons);
	jint _port = (jint)port;
	(*env)->CallVoidMethod(env, o, mid_HTTPClient_TrySocks5, _port);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPRequest_allowInsecure(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	proxylibcore_HTTPRequest_AllowInsecure(o);
}

void cproxylibcore_HTTPRequest_AllowInsecure(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPRequest, proxy_class_libcore_HTTPRequest_cons);
	(*env)->CallVoidMethod(env, o, mid_HTTPRequest_AllowInsecure);
	go_seq_pop_local_frame(env);
}

JNIEXPORT jobject JNICALL
Java_libcore_Libcore_00024proxyHTTPRequest_execute(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	struct proxylibcore_HTTPRequest_Execute_return res = proxylibcore_HTTPRequest_Execute(o);
	jobject _r0 = go_seq_from_refnum(env, res.r0, proxy_class_libcore_HTTPResponse, proxy_class_libcore_HTTPResponse_cons);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

struct cproxylibcore_HTTPRequest_Execute_return cproxylibcore_HTTPRequest_Execute(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPRequest, proxy_class_libcore_HTTPRequest_cons);
	jobject res = (*env)->CallObjectMethod(env, o, mid_HTTPRequest_Execute);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	if (exc != NULL) {
		res = NULL;
	}
	int32_t _res = go_seq_to_refnum(env, res);
	cproxylibcore_HTTPRequest_Execute_return sres = {
		_res, _exc
	};
	go_seq_pop_local_frame(env);
	return sres;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPRequest_setContent(JNIEnv* env, jobject __this__, jbyteArray content) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nbyteslice _content = go_seq_from_java_bytearray(env, content, 0);
	proxylibcore_HTTPRequest_SetContent(o, _content);
	go_seq_release_byte_array(env, content, _content.ptr);
}

void cproxylibcore_HTTPRequest_SetContent(int32_t refnum, nbyteslice content) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPRequest, proxy_class_libcore_HTTPRequest_cons);
	jbyteArray _content = go_seq_to_java_bytearray(env, content, 0);
	(*env)->CallVoidMethod(env, o, mid_HTTPRequest_SetContent, _content);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPRequest_setContentString(JNIEnv* env, jobject __this__, jstring content) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _content = go_seq_from_java_string(env, content);
	proxylibcore_HTTPRequest_SetContentString(o, _content);
}

void cproxylibcore_HTTPRequest_SetContentString(int32_t refnum, nstring content) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPRequest, proxy_class_libcore_HTTPRequest_cons);
	jstring _content = go_seq_to_java_string(env, content);
	(*env)->CallVoidMethod(env, o, mid_HTTPRequest_SetContentString, _content);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPRequest_setHeader(JNIEnv* env, jobject __this__, jstring key, jstring value) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _key = go_seq_from_java_string(env, key);
	nstring _value = go_seq_from_java_string(env, value);
	proxylibcore_HTTPRequest_SetHeader(o, _key, _value);
}

void cproxylibcore_HTTPRequest_SetHeader(int32_t refnum, nstring key, nstring value) {
	JNIEnv *env = go_seq_push_local_frame(2);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPRequest, proxy_class_libcore_HTTPRequest_cons);
	jstring _key = go_seq_to_java_string(env, key);
	jstring _value = go_seq_to_java_string(env, value);
	(*env)->CallVoidMethod(env, o, mid_HTTPRequest_SetHeader, _key, _value);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPRequest_setMethod(JNIEnv* env, jobject __this__, jstring method) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _method = go_seq_from_java_string(env, method);
	proxylibcore_HTTPRequest_SetMethod(o, _method);
}

void cproxylibcore_HTTPRequest_SetMethod(int32_t refnum, nstring method) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPRequest, proxy_class_libcore_HTTPRequest_cons);
	jstring _method = go_seq_to_java_string(env, method);
	(*env)->CallVoidMethod(env, o, mid_HTTPRequest_SetMethod, _method);
	go_seq_pop_local_frame(env);
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPRequest_setURL(JNIEnv* env, jobject __this__, jstring link) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _link = go_seq_from_java_string(env, link);
	int32_t r0 = proxylibcore_HTTPRequest_SetURL(o, _link);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

int32_t cproxylibcore_HTTPRequest_SetURL(int32_t refnum, nstring link) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPRequest, proxy_class_libcore_HTTPRequest_cons);
	jstring _link = go_seq_to_java_string(env, link);
	(*env)->CallVoidMethod(env, o, mid_HTTPRequest_SetURL, _link);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	go_seq_pop_local_frame(env);
	return _exc;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPRequest_setUserAgent(JNIEnv* env, jobject __this__, jstring userAgent) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _userAgent = go_seq_from_java_string(env, userAgent);
	proxylibcore_HTTPRequest_SetUserAgent(o, _userAgent);
}

void cproxylibcore_HTTPRequest_SetUserAgent(int32_t refnum, nstring userAgent) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPRequest, proxy_class_libcore_HTTPRequest_cons);
	jstring _userAgent = go_seq_to_java_string(env, userAgent);
	(*env)->CallVoidMethod(env, o, mid_HTTPRequest_SetUserAgent, _userAgent);
	go_seq_pop_local_frame(env);
}

JNIEXPORT jbyteArray JNICALL
Java_libcore_Libcore_00024proxyHTTPResponse_getContent(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	struct proxylibcore_HTTPResponse_GetContent_return res = proxylibcore_HTTPResponse_GetContent(o);
	jbyteArray _r0 = go_seq_to_java_bytearray(env, res.r0, 1);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

struct cproxylibcore_HTTPResponse_GetContent_return cproxylibcore_HTTPResponse_GetContent(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPResponse, proxy_class_libcore_HTTPResponse_cons);
	jbyteArray res = (*env)->CallObjectMethod(env, o, mid_HTTPResponse_GetContent);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	if (exc != NULL) {
		res = NULL;
	}
	nbyteslice _res = go_seq_from_java_bytearray(env, res, 1);
	cproxylibcore_HTTPResponse_GetContent_return sres = {
		_res, _exc
	};
	go_seq_pop_local_frame(env);
	return sres;
}

JNIEXPORT jobject JNICALL
Java_libcore_Libcore_00024proxyHTTPResponse_getContentString(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	struct proxylibcore_HTTPResponse_GetContentString_return res = proxylibcore_HTTPResponse_GetContentString(o);
	jobject _r0 = go_seq_from_refnum(env, res.r0, proxy_class_libcore_StringBox, proxy_class_libcore_StringBox_cons);
	jobject _r1 = go_seq_from_refnum(env, res.r1, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r1);
	return _r0;
}

struct cproxylibcore_HTTPResponse_GetContentString_return cproxylibcore_HTTPResponse_GetContentString(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPResponse, proxy_class_libcore_HTTPResponse_cons);
	jobject res = (*env)->CallObjectMethod(env, o, mid_HTTPResponse_GetContentString);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	if (exc != NULL) {
		res = NULL;
	}
	int32_t _res = go_seq_to_refnum(env, res);
	cproxylibcore_HTTPResponse_GetContentString_return sres = {
		_res, _exc
	};
	go_seq_pop_local_frame(env);
	return sres;
}

JNIEXPORT jobject JNICALL
Java_libcore_Libcore_00024proxyHTTPResponse_getHeader(JNIEnv* env, jobject __this__, jstring p0) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _p0 = go_seq_from_java_string(env, p0);
	int32_t r0 = proxylibcore_HTTPResponse_GetHeader(o, _p0);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class_libcore_StringBox, proxy_class_libcore_StringBox_cons);
	return _r0;
}

int32_t cproxylibcore_HTTPResponse_GetHeader(int32_t refnum, nstring p0) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPResponse, proxy_class_libcore_HTTPResponse_cons);
	jstring _p0 = go_seq_to_java_string(env, p0);
	jobject res = (*env)->CallObjectMethod(env, o, mid_HTTPResponse_GetHeader, _p0);
	int32_t _res = go_seq_to_refnum(env, res);
	go_seq_pop_local_frame(env);
	return _res;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyHTTPResponse_writeTo(JNIEnv* env, jobject __this__, jstring path) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _path = go_seq_from_java_string(env, path);
	int32_t r0 = proxylibcore_HTTPResponse_WriteTo(o, _path);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

int32_t cproxylibcore_HTTPResponse_WriteTo(int32_t refnum, nstring path) {
	JNIEnv *env = go_seq_push_local_frame(1);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_HTTPResponse, proxy_class_libcore_HTTPResponse_cons);
	jstring _path = go_seq_to_java_string(env, path);
	(*env)->CallVoidMethod(env, o, mid_HTTPResponse_WriteTo, _path);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	go_seq_pop_local_frame(env);
	return _exc;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyLocalDNSTransport_exchange(JNIEnv* env, jobject __this__, jobject ctx, jbyteArray message) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t _ctx = go_seq_to_refnum(env, ctx);
	nbyteslice _message = go_seq_from_java_bytearray(env, message, 0);
	int32_t r0 = proxylibcore_LocalDNSTransport_Exchange(o, _ctx, _message);
	go_seq_release_byte_array(env, message, _message.ptr);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

int32_t cproxylibcore_LocalDNSTransport_Exchange(int32_t refnum, int32_t ctx, nbyteslice message) {
	JNIEnv *env = go_seq_push_local_frame(2);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_LocalDNSTransport, proxy_class_libcore_LocalDNSTransport_cons);
	jobject _ctx = go_seq_from_refnum(env, ctx, proxy_class_libcore_ExchangeContext, proxy_class_libcore_ExchangeContext_cons);
	jbyteArray _message = go_seq_to_java_bytearray(env, message, 0);
	(*env)->CallVoidMethod(env, o, mid_LocalDNSTransport_Exchange, _ctx, _message);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	go_seq_pop_local_frame(env);
	return _exc;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyLocalDNSTransport_lookup(JNIEnv* env, jobject __this__, jobject ctx, jstring network, jstring domain) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int32_t _ctx = go_seq_to_refnum(env, ctx);
	nstring _network = go_seq_from_java_string(env, network);
	nstring _domain = go_seq_from_java_string(env, domain);
	int32_t r0 = proxylibcore_LocalDNSTransport_Lookup(o, _ctx, _network, _domain);
	jobject _r0 = go_seq_from_refnum(env, r0, proxy_class__error, proxy_class__error_cons);
	go_seq_maybe_throw_exception(env, _r0);
}

int32_t cproxylibcore_LocalDNSTransport_Lookup(int32_t refnum, int32_t ctx, nstring network, nstring domain) {
	JNIEnv *env = go_seq_push_local_frame(3);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_LocalDNSTransport, proxy_class_libcore_LocalDNSTransport_cons);
	jobject _ctx = go_seq_from_refnum(env, ctx, proxy_class_libcore_ExchangeContext, proxy_class_libcore_ExchangeContext_cons);
	jstring _network = go_seq_to_java_string(env, network);
	jstring _domain = go_seq_to_java_string(env, domain);
	(*env)->CallVoidMethod(env, o, mid_LocalDNSTransport_Lookup, _ctx, _network, _domain);
	jobject exc = go_seq_get_exception(env);
	int32_t _exc = go_seq_to_refnum(env, exc);
	go_seq_pop_local_frame(env);
	return _exc;
}

JNIEXPORT jlong JNICALL
Java_libcore_Libcore_00024proxyLocalDNSTransport_networkHandle(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	int64_t r0 = proxylibcore_LocalDNSTransport_NetworkHandle(o);
	jlong _r0 = (jlong)r0;
	return _r0;
}

int64_t cproxylibcore_LocalDNSTransport_NetworkHandle(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_LocalDNSTransport, proxy_class_libcore_LocalDNSTransport_cons);
	jlong res = (*env)->CallLongMethod(env, o, mid_LocalDNSTransport_NetworkHandle);
	int64_t _res = (int64_t)res;
	go_seq_pop_local_frame(env);
	return _res;
}

JNIEXPORT jboolean JNICALL
Java_libcore_Libcore_00024proxyLocalDNSTransport_raw(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	char r0 = proxylibcore_LocalDNSTransport_Raw(o);
	jboolean _r0 = r0 ? JNI_TRUE : JNI_FALSE;
	return _r0;
}

char cproxylibcore_LocalDNSTransport_Raw(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_LocalDNSTransport, proxy_class_libcore_LocalDNSTransport_cons);
	jboolean res = (*env)->CallBooleanMethod(env, o, mid_LocalDNSTransport_Raw);
	char _res = (char)res;
	go_seq_pop_local_frame(env);
	return _res;
}

JNIEXPORT void JNICALL
Java_libcore_Libcore_00024proxyNB4AInterface_selector_1OnProxySelected(JNIEnv* env, jobject __this__, jstring selectorTag, jstring tag) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	nstring _selectorTag = go_seq_from_java_string(env, selectorTag);
	nstring _tag = go_seq_from_java_string(env, tag);
	proxylibcore_NB4AInterface_Selector_OnProxySelected(o, _selectorTag, _tag);
}

void cproxylibcore_NB4AInterface_Selector_OnProxySelected(int32_t refnum, nstring selectorTag, nstring tag) {
	JNIEnv *env = go_seq_push_local_frame(2);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_NB4AInterface, proxy_class_libcore_NB4AInterface_cons);
	jstring _selectorTag = go_seq_to_java_string(env, selectorTag);
	jstring _tag = go_seq_to_java_string(env, tag);
	(*env)->CallVoidMethod(env, o, mid_NB4AInterface_Selector_OnProxySelected, _selectorTag, _tag);
	go_seq_pop_local_frame(env);
}

JNIEXPORT jboolean JNICALL
Java_libcore_Libcore_00024proxyNB4AInterface_useOfficialAssets(JNIEnv* env, jobject __this__) {
	int32_t o = go_seq_to_refnum_go(env, __this__);
	char r0 = proxylibcore_NB4AInterface_UseOfficialAssets(o);
	jboolean _r0 = r0 ? JNI_TRUE : JNI_FALSE;
	return _r0;
}

char cproxylibcore_NB4AInterface_UseOfficialAssets(int32_t refnum) {
	JNIEnv *env = go_seq_push_local_frame(0);
	jobject o = go_seq_from_refnum(env, refnum, proxy_class_libcore_NB4AInterface, proxy_class_libcore_NB4AInterface_cons);
	jboolean res = (*env)->CallBooleanMethod(env, o, mid_NB4AInterface_UseOfficialAssets);
	char _res = (char)res;
	go_seq_pop_local_frame(env);
	return _res;
}

